{% set name = "cereal" %}
{% set version = "1.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/USCiLab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 329ea3e3130b026c03a4acc50e168e7daff4e6e661bc6a7dfec0d77b570851d5

  patches:
    # remove cxx compiler dependency
    - no-compiler.patch

build:
  noarch: generic
  number: 0

requirements:
  build:
    - cmake

test:
  commands:
    - test -f $PREFIX/include/cereal/cereal.hpp  # [not win]
    - if not exist %LIBRARY_INC%\\cereal\\cereal.hpp exit 1  # [win]

about:
  home: http://uscilab.github.io/cereal/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A C++11 library for serialization'
  doc_url: http://uscilab.github.io/cereal/
  dev_url: http://github.com/USCiLab/cereal

extra:
  recipe-maintainers:
    - saraedum
    - joaander
