travis:
  secure:
    BINSTAR_TOKEN: YLO2UR4iy1eY0yR46Lr8TM32zjfpU2DL6IZD+4sEOxuWCQmiB9XYIyEr5A3l5yJSUmBRSVZaMfv4cTT6n8QvdelENSdMSnggvVMprlYOKr62vMt80FLh7KxnOEYcTcdPu9tBnFli9MU5Rd5PjUP+R3vJDUwn4F9CwFV6l7O6oTk8kO42mTcmXc2IU94Ia3/od7qL+lExwEP9pdtyVPNf14v6dOurvWUml6BRnFhY4r8BRoNv/XgPlbBY8rY1j6QVHKOZPYaXaira/T5PZhqMS7uP0fjAPmxSPgUIpAAIE+DANM1m39mKFS6GqlfsljDy92mc9JI9oP9EKHoEidmeCQzhB/QThvsCBzeJ7Ew2LsWeK+0OBMuRl+Y/Uoz8Q+ZLfjtO2Jd2lBQM7nx/mdZwR2pBnqPxHcrNcNi+O18mpMrrvqde2AjbdkCetOVborX01erRtHiepdchq5uSq5iINY4A0biaCAcEcYQ4iujwjITvUTLBePVdn8+dRCtW79/m/uX/432N3hHR/54AzLdSQBhf+gBq8XY4L6vjyd3ahzlTIpuJvvoVAEmnYBmbEOMZPfLJa5UfAPcdlOW+LeB8K9Let1zT3VFokX93KKDxYzWs5mDmQKACcZsJ4vEE9luiYWXUxHwvUP3DPujSV46qWFJL61F4t4YVAiAA8FPNjL0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
